### ISSUE TITLE
Ip Proxy Reverse

### ISSUE THREAD

**Issue by x71hicks** [msmolka/ZNetCS.AspNetCore.IPFiltering#6]
Thanks for your contribution, I have a configuration where the web api receives a request only from a reverse proxy, but in the console it shows me the IP of the final client and I want to validate the IP of the proxy in this case, is it possible?

**Comment by msmolka** [comment]
As you can see here:
https://github.com/msmolka/ZNetCS.AspNetCore.IPFiltering/blob/da50095af7dcf6b943564cb39c002020bb899e60/src/ZNetCS.AspNetCore.IPFiltering/Internal/IPAddressFinder.cs#L94

The idea is to block client IP not proxy one. Because there can be multiple proxies on the way.

However, if you only want to make sure that final proxy is yours you have couple options:
a) set X-Real-IP in your proxy. it will take precedence during validation. https://github.com/msmolka/ZNetCS.AspNetCore.IPFiltering/blob/da50095af7dcf6b943564cb39c002020bb899e60/src/ZNetCS.AspNetCore.IPFiltering/Internal/IPAddressFinder.cs#L78
b) add custom middleware BEFORE IpFiltering one which will rewrite X-Forwarded-For header with only last value: which is your proxy
c) write your own implementation of IIPAddressFinder interface:
https://github.com/msmolka/ZNetCS.AspNetCore.IPFiltering/blob/da50095af7dcf6b943564cb39c002020bb899e60/src/ZNetCS.AspNetCore.IPFiltering/Internal/IPAddressFinder.cs#L27

**Comment by x71hicks** [comment]
> As you can see here:
> 
> https://github.com/msmolka/ZNetCS.AspNetCore.IPFiltering/blob/da50095af7dcf6b943564cb39c002020bb899e60/src/ZNetCS.AspNetCore.IPFiltering/Internal/IPAddressFinder.cs#L94
> 
> The idea is to block client IP not proxy one. Because there can be multiple proxies on the way.
> 
> However, if you only want to make sure that final proxy is yours you have couple options: a) set X-Real-IP in your proxy. it will take precedence during validation.
> 
> https://github.com/msmolka/ZNetCS.AspNetCore.IPFiltering/blob/da50095af7dcf6b943564cb39c002020bb899e60/src/ZNetCS.AspNetCore.IPFiltering/Internal/IPAddressFinder.cs#L78
> 
> b) add custom middleware BEFORE IpFiltering one which will rewrite X-Forwarded-For header with only last value: which is your proxy
> c) write your own implementation of IIPAddressFinder interface:
> 
> https://github.com/msmolka/ZNetCS.AspNetCore.IPFiltering/blob/da50095af7dcf6b943564cb39c002020bb899e60/src/ZNetCS.AspNetCore.IPFiltering/Internal/IPAddressFinder.cs#L27

thank you very much!!!!
